site_name: CategorAIze Docs
site_description: Documentation for CategorAIze
site_url: https://moneycluster.github.io/CategorAIze/

repo_name: moneycluster/CategorAIze
repo_url: https://github.com/moneycluster/CategorAIze
edit_uri: edit/main/docs/

docs_dir: docs

theme:
  name: material
  language: ru
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.action.edit
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: indigo
      accent: indigo
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: indigo
      accent: indigo

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
        - name: plantuml
          class: plantuml
        - name: puml
          class: plantuml
  - pymdownx.details

plugins:
  - search
  - escape-macros
  - macros:
      modules:
        - docs._macros.main
  - include-markdown
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      puml_keyword: plantuml
      theme:
        enabled: false

nav:
  - Введение: index.md
  - Руководства:
      - Работа с документацией: guides/documentation.md
  - Архитектурные решения (ADR):
      - Обзор: adr/index.md
      - adr/001-global-adr.md
      - adr/002-personalized-classification.md


extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - _assets/mermaid-init.js
  - _static/likec4/likec4-views.js

extra_css:
  - _assets/plantuml.css
